Feat/cli/react multitenancy
supertokens/create-supertokens-app pull request #131
Opened 2024-12-15 10:19 UTC by ConzorKingKong

## Summary of change

Updates React multitenancy upgrades to be boilerplate

## Test plan

-   [ ] If added a new boilerplate
    -   I tested the new boilerplate by running the CLI locally
    -   I tested that the boilerplate is created and works correctly when using command line flags (`--recipe=...` for example)
-   [ ] If added a new recipe, frontend or backend
    -   I tested that the newly added option is usable by passing command line flags (`--recipe=...` for example)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] If added a new recipe, I also modified types to include the new recipe in `Recipe` and `allRecipes`
-   [ ] If added a new frontend, I also modified types to include the new frontend in `SupportedFrontends` and `allFrontends` if required
-   [ ] If added a new backend, I also modified types to include the new backend in `SupportedBackends` and `allBackends` if required

## Remaining TODOs for this PR

-   [ ] Make project work after boilerplate folder rename

2024-12-15 10:25 UTC, ConzorKingKong commented
Running npx create-supertokens-app --branch=feat/cli/react-multitenancy doesn't work - forces version 0.0.55 and gives this error:

```
Error: Error: ENOENT: no such file or directory, rename '/Users/connor/projects/supertokens/tools/f/supertokens-react-multitenancy' -> '/Users/connor/projects/supertokens/tools/f/frontend'
  at Object.renameSync (node:fs:1032:11)
  at setupFrontendBackendApp (file:///Users/connor/.npm/_npx/f43f4c5b1dac493a/node_modules/create-supertokens-app/lib/build/utils.js:241:8)
  at setupProject (file:///Users/connor/.npm/_npx/f43f4c5b1dac493a/node_modules/create-supertokens-app/lib/build/utils.js:517:15)
  at run (file:///Users/connor/.npm/_npx/f43f4c5b1dac493a/node_modules/create-supertokens-app/lib/build/index.js:175:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


Error: If you think this is an issue with the tool, please report this as an issue at https://github.com/supertokens/create-supertokens-app/issues
```

Running locally with npx . Gives version 0.0.57 (version I set) and gives this error instead:

```
Error: Error: ENOENT: no such file or directory, rename '/Users/connor/projects/supertokens/create-supertokens-app/testmulti/react-multitenancy' -> '/Users/connor/projects/supertokens/create-supertokens-app/testmulti/frontend'
  at Object.renameSync (node:fs:1032:11)
  at setupFrontendBackendApp (file:///Users/connor/projects/supertokens/create-supertokens-app/lib/build/utils.js:241:8)
  at setupProject (file:///Users/connor/projects/supertokens/create-supertokens-app/lib/build/utils.js:517:15)
  at run (file:///Users/connor/projects/supertokens/create-supertokens-app/lib/build/index.js:175:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


Error: If you think this is an issue with the tool, please report this as an issue at https://github.com/supertokens/create-supertokens-app/issues
```

2025-01-02 19:41 UTC, porcellus approved these changes

2025-01-02 19:55 UTC, porcellus requested changes

2025-01-02 19:55 UTC, porcellus commented on boilerplate/frontend/react-multitenancy/src/Home/index.tsx
> +                        </a>
This is inconsitent with the latest changes in [this PR](https://github.com/supertokens/create-supertokens-app/pull/132/files#)

2025-01-02 19:55 UTC, porcellus commented on boilerplate/frontend/react-multitenancy/config/multitenancy.tsx
> +        }
This is inconsistent with the latest changes in [this PR](https://github.com/supertokens/create-supertokens-app/pull/132/files#)

2025-01-08 18:08 UTC, ConzorKingKong commented on boilerplate/frontend/react-multitenancy/config/multitenancy.tsx
> +        }
fixed

2025-01-08 18:10 UTC, ConzorKingKong commented on boilerplate/frontend/react-multitenancy/src/Home/index.tsx
> +                        </a>
Apologies, I missed a couple things from the refactor and didn't realize. I pushed up a change for this but I need to re-fix the css and move some logic around to match. I'll get this done today or tomorrow

2025-01-15 06:33 UTC, ConzorKingKong commented on boilerplate/frontend/react-multitenancy/src/Home/index.tsx
> +                        </a>
This specific error is fixed

2025-01-15 06:35 UTC, ConzorKingKong commented
There are still 2 problems that need to be fixed:

1. CSS errors on /auth
2. Proper comments in CSS file

I'll get these tomorrow

2025-05-19 13:04 UTC, closed without merging