feat: eliminated duplicate init call need for non-react apps
supertokens/create-supertokens-app pull request #49
Opened 2023-01-18 11:37 UTC by alisher-aituarov

Removed duplicate supertokens init calls for angular|vue boilerplate apps

2023-01-18 17:41 UTC, porcellus requested changes

2023-01-18 17:41 UTC, porcellus commented on boilerplate/frontend/angular-prebuilt/README.md
> +-   Since `supertokens-auth-react` SDK uses `supertokens-web-js` underneath we only need to initialize `supertokens-auth-react` on the main route.
I'm not sure if this line needs to be here anymore.

2023-01-20 20:47 UTC, porcellus approved these changes

2023-02-03 06:55 UTC, rishabhpoddar requested changes

2023-02-03 06:55 UTC, rishabhpoddar commented on boilerplate/frontend/angular-prebuilt/README.md
>  -   Forgot password flow
the boilerplates need to be updated to use the new way of adding the pre built UI

2023-05-03 09:39 UTC, rishabhpoddar commented on lib/ts/utils.ts
requires version change

2023-05-03 09:50 UTC, nkshah2 approved these changes

2023-05-03 10:22 UTC, rishabhpoddar requested changes

2023-05-03 10:22 UTC, rishabhpoddar commented on boilerplate/fullstack/next/pages/auth/[[...path]].tsx
>  const SuperTokensComponentNoSSR = dynamic<React.ComponentProps<typeof SuperTokens.getRoutingComponent>>(
```suggestion
const SuperTokensComponentNoSSR = dynamic<{}>(
```

2023-05-03 10:25 UTC, rishabhpoddar approved these changes

2023-05-03 10:25 UTC, merged